Fresh_food_E_commerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

apps/df_cart/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from . import views

app_name = 'df_cart'

urlpatterns = [
    url(r'^$', views.user_cart, name="cart"),
    url(r'^add(\d+)_(\d+)/$', views.add, name="add"),
    url(r'^edit(\d+)_(\d+)/$', views.edit, name="edit"),
    url(r'^delete(\d+)/$', views.delete, name="delete"),
]

apps/df_goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
]

templates/base.html
{% extends 'base_foot.html' %}

{% block body %}

    <div class="header_con">
		<div class="header">
			<div class="welcome fl">Welcome to Fresh Food Store!</div>
			<div class="fr">
            {# check if user has logged in #}
                {% if request.session.user_name|default:'' != '' %}
{# default filter checks if request.session.user_name not equal to null, which means user's logging
                    in is true #}

{# class="login_info fl"#}

				<div class="login_btn fl">Welcome：<em>{{ request.session.user_name }}</em>
                    <span>|</span>
                    <em><a href="{% url "df_user:logout" %}">Log out</a></em>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url "df_user:login" %}">Log in</a>
					<span>|</span>
					<a href="{% url "df_user:register" %}">Register</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url "df_user:info" %}">User center</a>
					<span>|</span>
					<a href="{% url "df_cart:cart" %}">My cart</a>
					<span>|</span>
					<a href="{% url "df_user:order" 1 %}">My order</a>
				</div>
			</div>
		</div>
	</div>


    <div class="search_bar clearfix">
		<a href="/" class="logo fl"><img src="/static/images/logo.png"></a>
        {% if page_name == 1 %}
            <div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{{ title }}</div>
        {% endif %}
		<div class="search_con fl">
             <script>
                $(function () {
                    $('.input_btn').click(function () {
                        q = $('.input_text').val();
                        if(q==""){
                        alert("Please enter what you want to purchase");
                        }
                        else{
                            location.href = '{% url "df_goods:ordinary_search" %}?q='+q+'&page=1'
                        }
                    })
                })

            </script>
			<input type="text" class="input_text fl" name="q" placeholder="Search commodity">
			<input type="button" class="input_btn fr" name="" value="search">
		</div>

        {% if guest_cart == 1 %}
            <div class="guest_cart fr">
                <a href="{% url "df_cart:cart" %}" class="cart_name fl">My cart</a>
                <div class="goods_count fl" id="show_count">{{ cart_num }}</div>
            </div>
        {% endif %}
	</div>




{% block content %}
{% endblock content %}
{% block center_body %}

{% endblock center_body %}


{% endblock body %}

templates/base_foot.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>{{ title }} | Fresh Food Store </title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
{#	<script type="text/javascript" src="/static/js/register.js"></script>#}
    {% block head %}{% endblock head %}
</head>
<body>

{% block body %}{% endblock body %}

    <div class="footer no-mp">
		<div class="foot_link">
			<a href="https://github.com/ZJW-92/Fresh_food_E-commerce">About store</a>
			<span>|</span>
			<a href="https://github.com/ZJW-92/Fresh_food_E-commerce">Contact</a>
			<span>|</span>
			<a href="#">Swish</a>
			<span>|</span>
			<a href="#">Links</a>
		</div>
		<p>CopyRight © 2018 All Rights Reserved</p>
	</div>

</body>
</html>

templates/cart.html
{% extends 'base.html' %}

{% block head %}
<script>

    $(function () {
        total();
        {#    choose all or remove all #}
        $('#check_all').click(function () {
    {#        get current state #}

            state=$(this).prop('checked');
            $(':checkbox:not(#ckeck_all)').prop('checked',state)
        });

        $(':checkbox:not(#check_all)').click(function () {
            if($(this).prop('checked')){
{#                alert($(':checked').length);#}
                if($(':checked').length+1==$(':checkbox').length){
                    $('#ckeck_all').prop('checked',true);
                }
            }
            else{
                $('#check_all').prop('checked',false)
            }
        });

        $('.add').click(function () {

            txt=$(this).next();
            txt.val(parseFloat(txt.val())+1).blur();

        });
         $('.minus').click(function () {
            txt=$(this).prev();
             txt.val(parseFloat(txt.val())-1).blur()
        });

        $('.num_show').blur(function () {
            count=parseFloat($(this).val());
            kucun=parseFloat($(this).attr('kucun'));
            if(count<1){
                alert('Amount cannot be zero');
                $(this).val(1);
                count = 1;
                $(this).focus();
                return;
            }
            else if(count>kucun){
             alert('Amount exceeds stock ');
             $(this).val(kucun);
             count = kucun;
             $(this).focus();
             return;
            }

            cart_id = $(this).parents('.cart_list_td').attr('id');
            $.get('/cart/edit'+cart_id+'_'+count+'/',function (data) {
                if(data.count==0){
                    total();
                }
                else {
                    $(this).val(data.count)
                }
            })
        })
    });
    function cart_del(cart_id) {
            del = confirm('delete');
{#            cart_id = $(this).parents('.cart_list_td').attr('id');#}
{#            alert(cart_id);#}
            if(del){
                $.get('/cart/delete'+cart_id+'/',function (data) {
{#                    alert(data.ok);#}
                    if(data.ok==1){
                        $('ul').remove('#'+cart_id);
                        total();
                    }
                })
            }
        }
    function total(){
        total1=0;
        total_count=0;

            $('.col07').each(
                function () {

                //get amount
                count=$(this).prev().find('input').val();
                //get price per unit
                price = $(this).prev().prev().text();
                //calculate single price
                total0=parseFloat(count)*parseFloat(price);
                    $(this).text(total0.toFixed(2));
                //add to total price
                total1 += total0;
                total_count++;
            });
            $('#total').text(total1.toFixed(2));
            $('.total_count1').text(total_count);
        }
    function go_order() {
        s = '';
        $(':checked:not(#check_all)').each(function () {
             id = $(this).parents('.cart_list_td').attr('id');

             s = s +'cart_id='+id + '&'

        });


        s=s.substring(0,s.length-1);

        location.href = '/order?'+s ;

        }
</script>
{% endblock head %}

{% block center_body %}
	<div class="total_count">All commodities<em>{{ carts|length }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">Commodity name</li>
		<li class="col02">Comodity unit</li>
		<li class="col03">Comodity price per unit</li>
		<li class="col04">Amount</li>
		<li class="col05">Total</li>
		<li class="col06">Change</li>
	</ul>

    {% for cart in carts %}
	<ul class="cart_list_td clearfix" id="{{ cart.id }}">
		<li class="col01"><input type="checkbox" name="" id="check_goods" checked="checked"></li>
		<li class="col02"><img src="{{ MEDIA_URL }}{{ cart.goods.gpic }}"></li>
		<li class="col03">{{ cart.goods.gtitle }}<br><em>{{ cart.goods.gprice }}元/{{ cart.goods.gunit }}</em><br><em>库存：<span id="goods_kucun">{{ cart.goods.gkucun }}</span></em></li>
		<li class="col04">{{ cart.goods.gunit }}</li>
		<li class="col05">{{ cart.goods.gprice }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" class="num_show fl" value="{{ cart.count }}" kucun="{{ cart.goods.gkucun }}">
				<a href="javascript:;" class="minus fl">-</a>
			</div>
		</li>
		<li class="col07"></li>
		<li class="col08"><a href="javascript:cart_del({{ cart.id }});">删除</a></li>
	</ul>
    {% endfor %}

	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked="" id="check_all" href="javascript:;"></li>
		<li class="col02">Choose all</li>
		<li class="col03">Total(exclude feight )：<span>¥</span><em id="total"></em><br>共计<b class="total_count1"></b>items</li>
		<li class="col04"><a href="javascript:go_order()">Go to payment</a></li>
	</ul>

{% endblock center_body %}

templates/order.html
{% extends 'base.html' %}

{% block head %}
    <script>
    $(function () {
        $('.col07').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'元')
        })
    })
    </script>

{% endblock %}

{% block center_body %}
	
	<h3 class="common_title">Comfirm delivery address</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>Deliver to：</dt>
			<span><input type="radio" name="" checked="checked"></span>
            Current address：<span class="user_info_check">{{ user.uaddress }}</span>
            Recipient：<span class="user_info_check">{{ user.ushou }} </span>
            Tel：<span class="user_info_check">{{ user.uphone }}</span>
		</dl>
		<a href="{% url "df_user:site" %}" class="edit_site">Edit delivery address</a>

	</div>
	
	<h3 class="common_title">Payment</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked>
			<label class="cash">Klarna</label>
			<input type="radio" name="pay_style">
			<label class="weixin">Swish</label>
			<input type="radio" name="pay_style">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style">
			<label class="bank">Pay with bankcard</label>
		</div>
	</div>

	<h3 class="common_title">Commodity list</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">Commodity name </li>
			<li class="col02">Commodity unit</li>
			<li class="col03">Commodity price</li>
			<li class="col04">Amount</li>
			<li class="col05">Subtotal</li>
		</ul>
        {% for cart in carts %}
        <ul class="goods_list_td clearfix" id="{{ cart.id }}">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ MEDIA_URL }}{{ cart.goods.gpic }}"></li>
			<li class="col03">{{ cart.goods.gtitle }}</li>
			<li class="col04">{{ cart.goods.gunit }}</li>
			<li class="col05">{{ cart.goods.gprice }}</li>
			<li class="col06">{{ cart.count }}</li>
			<li class="col07">53.90SEK</li>
        </ul>
        {% endfor %}

	</div>

	<h3 class="common_title">Total price</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">Total<em>{{ carts|length }}</em>amount of commodities，Total price <b>{{ total_price }}</b></div>
			<div class="transit">Freight：<b>{{ trans_cost }}SEK</b></div>
			<div class="total_pay">Total：<b>{{ total_trans_price }}</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" id="order_btn">Submit order</a>
	</div>	

		<div class="popup_con">
		<div class="popup">
			<p>Success！Thank you for your payment! </p>
		</div>

		<div class="mask"></div>
	</div>

	<script type="text/javascript">
		$('#order_btn').click(function() {
		    $('.user_info_check').each(function () {
		        text = $(this).text();
				number = 0;
		        if (text == ''){
					number = 1;
				}
            });
			if (number == 1){
				alert('Pleaser enter valid delivery address');
				window.location.href = '{% url "df_user:site" %}';
			}

		    //get all id and concatenate into string
            cartids = '';
            $('.goods_list_td').each(function () {
               cartids = cartids + $(this).attr('id') +','
            });
		    cartids = cartids.substring(0,cartids.length-1);
		    total = {{ total_trans_price }};
		    data = {
		            'cart_ids':cartids,
                    'total':total,
                    'csrfmiddlewaretoken':'{{ csrf_token }}'
		    };

		    //send request
            $.post('/order/push/',data,function (data) {
                //succeed

                if (data.ok == 1){
                    localStorage.setItem('order_finish',2);

                    $('.popup_con').fadeIn('fast', function() {

                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){
                                window.location.href = '{% url "df_user:order" 1 %}';
                            });
                        },1000)
                    });
                }
                else {
                    alert('Failed to submit order!Try later.')
                }
            })
		});
	</script>
{% endblock center_body %}