Fresh_food_E_commerce/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.static import serve

from .settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('df_goods.urls', namespace='df_goods')),
    url(r'^user/', include('df_user.urls', namespace='df_user')),
    url(r'^cart/', include('df_cart.urls', namespace='df_cart')),
    url(r'^order/', include('df_order.urls', namespace='df_order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT})
]

apps/df_goods/urls.py
from django.conf.urls import url

from . import views

app_name = 'df_goods'

urlpatterns = [
    url('^$', views.index, name="index"),
    url('^list(\d+)_(\d+)_(\d+)/$', views.good_list, name="good_list"),
    url('^(\d+)/$', views.detail, name="detail"),
    url(r'^search/', views.ordinary_search, name="ordinary_search"),
]

apps/df_user/urls.py
#!/user/bin/env python
# -*- coding: utf-8 -*-
from django.conf.urls import url

from .views import *

app_name = 'df_user'

urlpatterns = [
    url(r'^register/$', register, name="register"),
    url(r'^register_handle/$', register_handle, name="register_handle"),
    url(r'^register_exist/$', register_exist, name="register_exist"),
    url(r'^login/$', login, name="login"),
    url(r'^login_handle/$', login_handle, name="login_handle"),
    url(r'^info/$', info, name="info"),
    url(r'^order/(\d+)$', order, name="order"),
    url(r'^site/$', site, name="site"),
    # url(r'^place_order/$', views.place_order),
    url(r'^logout/$', logout, name="logout"),
]

apps/df_order/models.py
from django.db import models

from df_goods.models import GoodsInfo
from df_user.models import UserInfo

class OrderInfo(models.Model):  # big order
    oid = models.CharField(max_length=20, primary_key=True, verbose_name="big order")
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE, verbose_name="order user")
    odate = models.DateTimeField(auto_now=True, verbose_name="time")
    oIsPay = models.BooleanField(default=False, verbose_name="paid or not")
    ototal = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="total price")
    oaddress = models.CharField(max_length=150, verbose_name="delivery address")

    class Meta:
        verbose_name = "order"
        verbose_name_plural = verbose_name

    def __str__(self):

        return "{0}on order {1}".format(self.user.uname, self.odate)


class OrderDetailInfo(models.Model):

    goods = models.ForeignKey(GoodsInfo, on_delete=models.CASCADE, verbose_name="commodity")
    order = models.ForeignKey(OrderInfo, on_delete=models.CASCADE, verbose_name="order")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="commodity price")
    count = models.IntegerField(verbose_name="piece")

    class Meta:
        verbose_name = "details"
        verbose_name_plural = verbose_name

    def __str__(self):
        # return self.goods.gtitle + "(数量为" + str(self.count)  + ")"
        return "{0}(number is {1})".format(self.goods.gtitle, self.count)

templates/user/login.html
{% extends 'base_foot.html' %}

{% block head %}
<script>
    $(function () {
        name_error = false;
        pwd_error = false;

        if({{ error_name }}==1){
            $('.user_error').html('User name is wrong').show();
        }
        if({{ error_pwd }}==1){
            $('.pwd_error').html('Password is wrong').show();
        }
        $('.name_input').blur(function () {
            if($('.name_input').val().length=0){
                $('.user_error').html('Please enter username').show();
                name_error = false;
            }else{
                $('.user_error').hide();
                name_error = true;
            }
        });
        $('.pass_input').blur(function () {
            if($('.pass_input').val().length=0){
                $('.pwd_error').html('Please enter password').show();
                pwd_error = false;
            }else{
                $('.pwd_error').hide();
                pwd_error = true;
            }
        })
    })
</script>
{% endblock head %}

{% block body %}
	<div class="login_top clearfix">
		<a href="{% url "df_goods:index" %}" class="login_logo"><img src="/static/images/logo02.png"></a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">Fast delivery</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>Log in</h1>
					<a href="{% url "df_user:register" %}">Register</a>
				</div>
				<div class="form_input">
					<form action="{% url "df_user:login_handle" %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="Enter username">
						<div class="user_error">Username is wrong.</div>
						<input type="password" name="pwd" class="pass_input" value="{{ password }}" placeholder="Enter password">
{#
						<div class="pwd_error">Password is wrong.</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="jizhu" value="1" checked="checked">
							<label>Remember username</label>
							<a href="#">Forget password</a>
						</div>
						<input type="submit" name="" value="Log in" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>

{% endblock body %}

templates/user/register.html
{% extends 'base_foot.html' %}

{% block head %}
    <script type="text/javascript" src="/static/js/register.js"></script>
    <script type="text/javascript">
    $(function(){

	var error_name = false;
	var error_password = false;
	var error_check_password = false;
	var error_email = false;
	var error_check = false;


	$('#user_name').blur(function() {
		check_user_name();
	});

	$('#pwd').blur(function() {
		check_pwd();
	});

	$('#cpwd').blur(function() {
		check_cpwd();
	});

	$('#email').blur(function() {
		check_email();
	});

	$('#allow').click(function() {
		if($(this).is(':checked'))
		{
			error_check = false;
			$(this).siblings('span').hide();
		}
		else
		{
			error_check = true;
			$(this).siblings('span').html('请勾选同意');
			$(this).siblings('span').show();
		}
	});


	function check_user_name(){
		var len = $('#user_name').val().length;

		if(len<5||len>20)
		{
			$('#user_name').next().html('Enter username with 5-20 characters');
			$('#user_name').next().show();
			error_name = true;

		}
		else
		{
			$.get('{% url "df_user:register_exist" %}?uname='+$('#user_name').val(),function(data){
                if (data.count >= 1) {
                    $('#user_name').next().html('Username is alreday existed.').show();
                    error_name = true;
                }else{
                    $('#user_name').next().hide();
                    error_name = false;
                }
            });
        }
	}

	function check_pwd(){
		var len = $('#pwd').val().length;
		if(len<4||len>20)
		{
			$('#pwd').next().html('Password should at least 4 digits.');
			$('#pwd').next().show();
			error_password = true;
		}
		else
		{
			$('#pwd').next().hide();
			error_password = false;
		}
	}


	function check_cpwd(){
		var pass = $('#pwd').val();
		var cpass = $('#cpwd').val();

		if(pass!=cpass)
		{
			$('#cpwd').next().html('Password doesnot match.');
			$('#cpwd').next().show();
			error_check_password = true;
		}
		else
		{
			$('#cpwd').next().hide();
			error_check_password = false;
		}

	}

	function check_email(){
		var re = /^[a-z0-9][\w\.\-]*@[a-z0-9\-]+(\.[a-z]{2,5}){1,2}$/;

		if(re.test($('#email').val()))
		{
			$('#email').next().hide();
			error_email = false;
		}
		else
		{
			$('#email').next().html('Email fomat is not correct.');
			$('#email').next().show();
			error_check_password = true;
		}

	}


	$('#reg_form').submit(function() {
		check_user_name();
		check_pwd();
		check_cpwd();
		check_email();

		if(error_name == false && error_password == false && error_check_password == false && error_email == false && error_check == false)
		{
			return true;
		}
		else
		{
			return false;
		}

	});
});
    </script>
{% endblock head %}

{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/logo02.png"></a>
			<div class="reg_slogan">Stay at home.</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>Register</h1>
				<a href="{% url "df_user:login" %}">Log in</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url "df_user:register_handle" %}" id='reg_form' method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>Username:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">Hint:</span>
					</li>
					<li>
						<label>Password:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">Hint:</span>
					</li>
					<li>
						<label>Vertify password:</label>
						<input type="password" name="confirm_pwd" id="cpwd">
						<span class="error_tip">Hint</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">Hint</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>Content《Fresh Food Store User Agreement》</label>
						<span class="error_tip2">Hint</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="Register">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

{% endblock body %}

templates/user/user_center_info.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>User center</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}" class="active">· User information</a></li>
				<li><a href="/user/order/1">· All orders</a></li>
				<li><a href="{% url "df_user:site" %}">· Delivery address</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">Information</h3>
						<ul class="user_info_list">
							<li><span>Username：</span>{{ user_name }}</li>
							<li><span>Tel：</span>{{ user_phone }}</li>
							<li><span>Address：</span>{{ user_address }}</li>
						</ul>
				</div>
            <h3 class="common_title2">{{ explain }}</h3>
            <div class="has_view_list">
                <ul class="goods_type_list clearfix">
                    {%  for good in goods_list %}
                    <li>
                        <a href="/{{ good.id }}/"><img src="{{ MEDIA_URL }}{{ good.gpic }}"></a>
                        <h4><a href="/{{ good.id }}/">{{ good.gtitle }}</a></h4>
                        <div class="operate">
                            <span class="prize">￥{{ good.gprice }}</span>
                            <span class="unit">{{ good.gprice }}/{{ good.gunit }}</span>
                            <a href="/cart/add{{ good.id }}_1/" class="add_goods" title="Add to cart"></a>
                        </div>
                    </li>
                    {% endfor %}
			</ul>
            </div>
		</div>
	</div>
{% endblock center_body %}

templates/user/user_center_order.html
{% extends 'base.html' %}

{% block center_body %}

	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url "df_user:info" %}">· Personal information</a></li>
				<li><a href="{% url "df_user:order" 1 %}" class="active">· All orders</a></li>
				<li><a href="{% url "df_user:site" %}">· Delivery address</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">All orders</h3>
                {% for orderinfo in page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ orderinfo.odate|date }}</li>
					<li class="col02">Order No：{{ orderinfo.oid }}</li>
					<li class="col02 stress">Has paid</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="55%">
                                {% for order_detail in orderinfo.orderdetailinfo_set.all %}
								<ul class="order_goods_list clearfix">					
									<li class="col01"><img src="{{ MEDIA_URL }}{{ order_detail.goods.gpic }}"></li>
                                    <li class="col02">{{ order_detail.goods.gtitle }}<em class="good_price">{{ order_detail.goods.gprice }}</em>元/<em>{{ order_detail.goods.gunit }}</em></li>
									<li class="col03">{{ order_detail.count }}piece</li>
									<li class="col04">101.80 SEK </li>
								</ul>
                                {% endfor %}
							</td>
							<td width="15%">{{ orderinfo.ototal }} SEK</td>
							<td width="15%">Has paid</td>
							<td width="15%"><a href="#" class="oper_btn">Check logistics </a></td>
						</tr>
					</tbody>
				</table>
			    {% endfor %}


				<div class="pagenation">
                    {% if page.has_previous %}
					    <a href="{% url "df_user:order" page.previous_page_number %}">Previous</a>
                    {% endif %}

                    {% for index in paginator.page_range %}
                        {% if index == page.number %}
                            <a href="{% url "df_user:order" index %}" class="active">{{ index }}</a>
                        {% else %}
                            <a href="{% url "df_user:order" index %}">{{ index }}</a>
                        {% endif %}
                    {% endfor %}

                    {% if page.has_next %}
					    <a href="{% url "df_user:order" page.next_page_number %}">Next></a>
                    {% endif %}
				</div>
		</div>
	</div>

    <script type="text/javascript">
    $(function () {
        $('.col04').each(function () {
            count = $(this).prev().text();
            price = $(this).prev().prev().find('.good_price').text();
            $(this).html(parseFloat(count,2)*parseFloat(price,2)+'SEK');
            }

        )
        }
    )

    </script>

{% endblock center_body %}

templates/user/user_center_site.html
{% extends 'base.html' %}

{% block center_body %}


	<div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
                <li><a href="{% url "df_user:info" %}">· Personal information</a></li>
				<li><a href="{% url "df_user:order" 1 %}">· All orders</a></li>
				<li><a href="{% url "df_user:site" %}" class="active">· Delivery address</a></li>
			</ul>
		</div>
		<div class="right_content clearfix">
				<h3 class="common_title2">Delivery address</h3>
				<div class="site_con">
					<dl>
                        <dt>Username：{{ user.ushou }}</dt>
                        <dt>Tel：{{ user.uphone }}</dt>
                        <dt>Current address：{{ user.uaddress }}</dt>
{#                        <a href="/user/place_order" style="display: block; width: 80px; height:30px; line-height: 30px; text-align: center;font-size: 13px; " class="info_submit">提交订单</a>#}
					</dl>
				</div>
				<h3 class="common_title2">Edit address:</h3>
				<div class="site_con">
					<form action="{% url "df_user:site" %}" method="post">
                        {% csrf_token %}
						<div class="form_group">
							<label>Recipient：</label>
							<input type="text" name="ushou" value="{{ user.ushou }}">
						</div>
                        <div class="form_group">
                            <label>Tel：</label>
                            <input type="text" name="uphone" value="{{ user.uphone }}">
                        </div>
                        <div class="form_group">
                            <label>Email：</label>
                            <input type="text" name="uyoubian" value="{{ user.uyoubian }}">
                        </div>
                        <div class="form_group form_group2">
                            <label>Address：</label>
                            <textarea class="site_area" name="uaddress" >{{ user.uaddress }}</textarea>
                        </div>
						<input type="submit" name="" value="Edit address" class="info_submit">
					</form>
				</div>
		</div>
	</div>


{% endblock center_body %}